spring.application.name=college-buddy
# Remove exclusions for Cohere auto-configuration
# Updated to use the Compose service name and internal port
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://collegedb.c3ykqq0umasr.eu-north-1.rds.amazonaws.com:5432/collegedb}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.model.chat.memory.jdbc.initialize-schema=true

jwt.secret=PPp27xSTfBwOpRn4/AV6gPzQSnQg+Oi80KdWfCcuAHs=
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
spring.ai.bedrock.aws.access-key=${AWS_ACCESS_KEY_ID}
spring.ai.bedrock.aws.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.ai.bedrock.aws.region=eu-north-1
spring.ai.bedrock.converse.chat.enabled=true
spring.ai.bedrock.converse.chat.options.model=anthropic.claude-3-5-sonnet-20240620-v1:0
logging.level.org.springframework.ai=DEBUG
spring.ai.model.embedding=bedrock-cohere
spring.ai.bedrock.cohere.embedding.enabled=true
spring.ai.bedrock.cohere.embedding.model-id=amazon.cohere-embed-english-v3
spring.ai.bedrock.titan.embedding.enabled=false
spring.ai.bedrock.titan.embedding.model-id=amazon.titan-embed-text-v2:0
spring.ai.bedrock.cohere.chat.enabled=false
spring.ai.bedrock.llama.chat.enabled=false
spring.ai.bedrock.jurassic2.chat.enabled=false